// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKoJweDffLv9O82LbisHaIz-Xpz_dxwGE',
    appId: '1:332837336527:web:68dbeb8943d047a8b68eba',
    messagingSenderId: '332837336527',
    projectId: 'viti-care-dc277',
    authDomain: 'viti-care-dc277.firebaseapp.com',
    storageBucket: 'viti-care-dc277.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUFF4tznYyA2hokyXMldhB-JTsCvoyhUg',
    appId: '1:332837336527:android:9baee12d81db719eb68eba',
    messagingSenderId: '332837336527',
    projectId: 'viti-care-dc277',
    storageBucket: 'viti-care-dc277.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCohfE1Mk6-CpkpyCuVGsHR_NB-lvVll2c',
    appId: '1:332837336527:ios:704b97f3fcfa1676b68eba',
    messagingSenderId: '332837336527',
    projectId: 'viti-care-dc277',
    storageBucket: 'viti-care-dc277.appspot.com',
    iosBundleId: 'com.error404.viticare.viticare',
  );
}
